// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package eventapplication.proxies;

public class Event
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject eventMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EventApplication.Event";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateTime("DateTime"),
		NumMaxRegistrants("NumMaxRegistrants"),
		NumRegistrants("NumRegistrants"),
		NumSpotsAvailable("NumSpotsAvailable"),
		Featured("Featured"),
		Event_EventDetails("EventApplication.Event_EventDetails"),
		Event_Location("EventApplication.Event_Location"),
		Event_Speaker("EventApplication.Event_Speaker");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Event(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EventApplication.Event"));
	}

	protected Event(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject eventMendixObject)
	{
		if (eventMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EventApplication.Event", eventMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EventApplication.Event");

		this.eventMendixObject = eventMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Event.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static eventapplication.proxies.Event initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return eventapplication.proxies.Event.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static eventapplication.proxies.Event initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new eventapplication.proxies.Event(context, mendixObject);
	}

	public static eventapplication.proxies.Event load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return eventapplication.proxies.Event.initialize(context, mendixObject);
	}

	public static java.util.List<eventapplication.proxies.Event> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<eventapplication.proxies.Event> result = new java.util.ArrayList<eventapplication.proxies.Event>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EventApplication.Event" + xpathConstraint))
			result.add(eventapplication.proxies.Event.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime()
	{
		return getDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTime
	 */
	public final java.util.Date getDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTime.toString());
	}

	/**
	 * Set value of DateTime
	 * @param datetime
	 */
	public final void setDateTime(java.util.Date datetime)
	{
		setDateTime(getContext(), datetime);
	}

	/**
	 * Set value of DateTime
	 * @param context
	 * @param datetime
	 */
	public final void setDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetime)
	{
		getMendixObject().setValue(context, MemberNames.DateTime.toString(), datetime);
	}

	/**
	 * @return value of NumMaxRegistrants
	 */
	public final java.lang.Integer getNumMaxRegistrants()
	{
		return getNumMaxRegistrants(getContext());
	}

	/**
	 * @param context
	 * @return value of NumMaxRegistrants
	 */
	public final java.lang.Integer getNumMaxRegistrants(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumMaxRegistrants.toString());
	}

	/**
	 * Set value of NumMaxRegistrants
	 * @param nummaxregistrants
	 */
	public final void setNumMaxRegistrants(java.lang.Integer nummaxregistrants)
	{
		setNumMaxRegistrants(getContext(), nummaxregistrants);
	}

	/**
	 * Set value of NumMaxRegistrants
	 * @param context
	 * @param nummaxregistrants
	 */
	public final void setNumMaxRegistrants(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer nummaxregistrants)
	{
		getMendixObject().setValue(context, MemberNames.NumMaxRegistrants.toString(), nummaxregistrants);
	}

	/**
	 * @return value of NumRegistrants
	 */
	public final java.lang.Integer getNumRegistrants()
	{
		return getNumRegistrants(getContext());
	}

	/**
	 * @param context
	 * @return value of NumRegistrants
	 */
	public final java.lang.Integer getNumRegistrants(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumRegistrants.toString());
	}

	/**
	 * Set value of NumRegistrants
	 * @param numregistrants
	 */
	public final void setNumRegistrants(java.lang.Integer numregistrants)
	{
		setNumRegistrants(getContext(), numregistrants);
	}

	/**
	 * Set value of NumRegistrants
	 * @param context
	 * @param numregistrants
	 */
	public final void setNumRegistrants(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numregistrants)
	{
		getMendixObject().setValue(context, MemberNames.NumRegistrants.toString(), numregistrants);
	}

	/**
	 * @return value of NumSpotsAvailable
	 */
	public final java.lang.Integer getNumSpotsAvailable()
	{
		return getNumSpotsAvailable(getContext());
	}

	/**
	 * @param context
	 * @return value of NumSpotsAvailable
	 */
	public final java.lang.Integer getNumSpotsAvailable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumSpotsAvailable.toString());
	}

	/**
	 * Set value of NumSpotsAvailable
	 * @param numspotsavailable
	 */
	public final void setNumSpotsAvailable(java.lang.Integer numspotsavailable)
	{
		setNumSpotsAvailable(getContext(), numspotsavailable);
	}

	/**
	 * Set value of NumSpotsAvailable
	 * @param context
	 * @param numspotsavailable
	 */
	public final void setNumSpotsAvailable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numspotsavailable)
	{
		getMendixObject().setValue(context, MemberNames.NumSpotsAvailable.toString(), numspotsavailable);
	}

	/**
	 * @return value of Featured
	 */
	public final java.lang.Boolean getFeatured()
	{
		return getFeatured(getContext());
	}

	/**
	 * @param context
	 * @return value of Featured
	 */
	public final java.lang.Boolean getFeatured(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Featured.toString());
	}

	/**
	 * Set value of Featured
	 * @param featured
	 */
	public final void setFeatured(java.lang.Boolean featured)
	{
		setFeatured(getContext(), featured);
	}

	/**
	 * Set value of Featured
	 * @param context
	 * @param featured
	 */
	public final void setFeatured(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean featured)
	{
		getMendixObject().setValue(context, MemberNames.Featured.toString(), featured);
	}

	/**
	 * @return value of Event_EventDetails
	 */
	public final eventapplication.proxies.EventDetails getEvent_EventDetails() throws com.mendix.core.CoreException
	{
		return getEvent_EventDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_EventDetails
	 */
	public final eventapplication.proxies.EventDetails getEvent_EventDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.EventDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Event_EventDetails.toString());
		if (identifier != null)
			result = eventapplication.proxies.EventDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Event_EventDetails
	 * @param event_eventdetails
	 */
	public final void setEvent_EventDetails(eventapplication.proxies.EventDetails event_eventdetails)
	{
		setEvent_EventDetails(getContext(), event_eventdetails);
	}

	/**
	 * Set value of Event_EventDetails
	 * @param context
	 * @param event_eventdetails
	 */
	public final void setEvent_EventDetails(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.EventDetails event_eventdetails)
	{
		if (event_eventdetails == null)
			getMendixObject().setValue(context, MemberNames.Event_EventDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Event_EventDetails.toString(), event_eventdetails.getMendixObject().getId());
	}

	/**
	 * @return value of Event_Location
	 */
	public final eventapplication.proxies.Location getEvent_Location() throws com.mendix.core.CoreException
	{
		return getEvent_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_Location
	 */
	public final eventapplication.proxies.Location getEvent_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Event_Location.toString());
		if (identifier != null)
			result = eventapplication.proxies.Location.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Event_Location
	 * @param event_location
	 */
	public final void setEvent_Location(eventapplication.proxies.Location event_location)
	{
		setEvent_Location(getContext(), event_location);
	}

	/**
	 * Set value of Event_Location
	 * @param context
	 * @param event_location
	 */
	public final void setEvent_Location(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.Location event_location)
	{
		if (event_location == null)
			getMendixObject().setValue(context, MemberNames.Event_Location.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Event_Location.toString(), event_location.getMendixObject().getId());
	}

	/**
	 * @return value of Event_Speaker
	 */
	public final eventapplication.proxies.Speaker getEvent_Speaker() throws com.mendix.core.CoreException
	{
		return getEvent_Speaker(getContext());
	}

	/**
	 * @param context
	 * @return value of Event_Speaker
	 */
	public final eventapplication.proxies.Speaker getEvent_Speaker(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.Speaker result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Event_Speaker.toString());
		if (identifier != null)
			result = eventapplication.proxies.Speaker.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Event_Speaker
	 * @param event_speaker
	 */
	public final void setEvent_Speaker(eventapplication.proxies.Speaker event_speaker)
	{
		setEvent_Speaker(getContext(), event_speaker);
	}

	/**
	 * Set value of Event_Speaker
	 * @param context
	 * @param event_speaker
	 */
	public final void setEvent_Speaker(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.Speaker event_speaker)
	{
		if (event_speaker == null)
			getMendixObject().setValue(context, MemberNames.Event_Speaker.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Event_Speaker.toString(), event_speaker.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return eventMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final eventapplication.proxies.Event that = (eventapplication.proxies.Event) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EventApplication.Event";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
