// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package eventapplication.proxies;

public class Login
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject loginMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EventApplication.Login";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Username("Username"),
		Login_Password("Login_Password"),
		Login_Registrant("EventApplication.Login_Registrant"),
		Login_Parent("EventApplication.Login_Parent"),
		Login_StudentDetails("EventApplication.Login_StudentDetails"),
		Login_Staff("EventApplication.Login_Staff");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Login(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EventApplication.Login"));
	}

	protected Login(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject loginMendixObject)
	{
		if (loginMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EventApplication.Login", loginMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EventApplication.Login");

		this.loginMendixObject = loginMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Login.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static eventapplication.proxies.Login initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return eventapplication.proxies.Login.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static eventapplication.proxies.Login initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new eventapplication.proxies.Login(context, mendixObject);
	}

	public static eventapplication.proxies.Login load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return eventapplication.proxies.Login.initialize(context, mendixObject);
	}

	public static java.util.List<eventapplication.proxies.Login> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<eventapplication.proxies.Login> result = new java.util.ArrayList<eventapplication.proxies.Login>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EventApplication.Login" + xpathConstraint))
			result.add(eventapplication.proxies.Login.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Login_Password
	 */
	public final java.lang.String getLogin_Password()
	{
		return getLogin_Password(getContext());
	}

	/**
	 * @param context
	 * @return value of Login_Password
	 */
	public final java.lang.String getLogin_Password(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Login_Password.toString());
	}

	/**
	 * Set value of Login_Password
	 * @param login_password
	 */
	public final void setLogin_Password(java.lang.String login_password)
	{
		setLogin_Password(getContext(), login_password);
	}

	/**
	 * Set value of Login_Password
	 * @param context
	 * @param login_password
	 */
	public final void setLogin_Password(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String login_password)
	{
		getMendixObject().setValue(context, MemberNames.Login_Password.toString(), login_password);
	}

	/**
	 * @return value of Login_Registrant
	 */
	public final eventapplication.proxies.Registrant getLogin_Registrant() throws com.mendix.core.CoreException
	{
		return getLogin_Registrant(getContext());
	}

	/**
	 * @param context
	 * @return value of Login_Registrant
	 */
	public final eventapplication.proxies.Registrant getLogin_Registrant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.Registrant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Login_Registrant.toString());
		if (identifier != null)
			result = eventapplication.proxies.Registrant.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Login_Registrant
	 * @param login_registrant
	 */
	public final void setLogin_Registrant(eventapplication.proxies.Registrant login_registrant)
	{
		setLogin_Registrant(getContext(), login_registrant);
	}

	/**
	 * Set value of Login_Registrant
	 * @param context
	 * @param login_registrant
	 */
	public final void setLogin_Registrant(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.Registrant login_registrant)
	{
		if (login_registrant == null)
			getMendixObject().setValue(context, MemberNames.Login_Registrant.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Login_Registrant.toString(), login_registrant.getMendixObject().getId());
	}

	/**
	 * @return value of Login_Parent
	 */
	public final eventapplication.proxies.Parent getLogin_Parent() throws com.mendix.core.CoreException
	{
		return getLogin_Parent(getContext());
	}

	/**
	 * @param context
	 * @return value of Login_Parent
	 */
	public final eventapplication.proxies.Parent getLogin_Parent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.Parent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Login_Parent.toString());
		if (identifier != null)
			result = eventapplication.proxies.Parent.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Login_Parent
	 * @param login_parent
	 */
	public final void setLogin_Parent(eventapplication.proxies.Parent login_parent)
	{
		setLogin_Parent(getContext(), login_parent);
	}

	/**
	 * Set value of Login_Parent
	 * @param context
	 * @param login_parent
	 */
	public final void setLogin_Parent(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.Parent login_parent)
	{
		if (login_parent == null)
			getMendixObject().setValue(context, MemberNames.Login_Parent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Login_Parent.toString(), login_parent.getMendixObject().getId());
	}

	/**
	 * @return value of Login_StudentDetails
	 */
	public final eventapplication.proxies.StudentDetails getLogin_StudentDetails() throws com.mendix.core.CoreException
	{
		return getLogin_StudentDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Login_StudentDetails
	 */
	public final eventapplication.proxies.StudentDetails getLogin_StudentDetails(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.StudentDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Login_StudentDetails.toString());
		if (identifier != null)
			result = eventapplication.proxies.StudentDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Login_StudentDetails
	 * @param login_studentdetails
	 */
	public final void setLogin_StudentDetails(eventapplication.proxies.StudentDetails login_studentdetails)
	{
		setLogin_StudentDetails(getContext(), login_studentdetails);
	}

	/**
	 * Set value of Login_StudentDetails
	 * @param context
	 * @param login_studentdetails
	 */
	public final void setLogin_StudentDetails(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.StudentDetails login_studentdetails)
	{
		if (login_studentdetails == null)
			getMendixObject().setValue(context, MemberNames.Login_StudentDetails.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Login_StudentDetails.toString(), login_studentdetails.getMendixObject().getId());
	}

	/**
	 * @return value of Login_Staff
	 */
	public final eventapplication.proxies.Staff getLogin_Staff() throws com.mendix.core.CoreException
	{
		return getLogin_Staff(getContext());
	}

	/**
	 * @param context
	 * @return value of Login_Staff
	 */
	public final eventapplication.proxies.Staff getLogin_Staff(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.Staff result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Login_Staff.toString());
		if (identifier != null)
			result = eventapplication.proxies.Staff.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Login_Staff
	 * @param login_staff
	 */
	public final void setLogin_Staff(eventapplication.proxies.Staff login_staff)
	{
		setLogin_Staff(getContext(), login_staff);
	}

	/**
	 * Set value of Login_Staff
	 * @param context
	 * @param login_staff
	 */
	public final void setLogin_Staff(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.Staff login_staff)
	{
		if (login_staff == null)
			getMendixObject().setValue(context, MemberNames.Login_Staff.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Login_Staff.toString(), login_staff.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return loginMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final eventapplication.proxies.Login that = (eventapplication.proxies.Login) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EventApplication.Login";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
