// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package eventapplication.proxies;

public class Parent
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject parentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EventApplication.Parent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Parent_Name("Parent_Name"),
		Parent_email("Parent_email"),
		phone_number("phone_number"),
		Parent_Registrant("EventApplication.Parent_Registrant");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Parent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EventApplication.Parent"));
	}

	protected Parent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parentMendixObject)
	{
		if (parentMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EventApplication.Parent", parentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EventApplication.Parent");

		this.parentMendixObject = parentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Parent.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static eventapplication.proxies.Parent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return eventapplication.proxies.Parent.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static eventapplication.proxies.Parent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new eventapplication.proxies.Parent(context, mendixObject);
	}

	public static eventapplication.proxies.Parent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return eventapplication.proxies.Parent.initialize(context, mendixObject);
	}

	public static java.util.List<eventapplication.proxies.Parent> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<eventapplication.proxies.Parent> result = new java.util.ArrayList<eventapplication.proxies.Parent>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EventApplication.Parent" + xpathConstraint))
			result.add(eventapplication.proxies.Parent.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Parent_Name
	 */
	public final java.lang.String getParent_Name()
	{
		return getParent_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_Name
	 */
	public final java.lang.String getParent_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Parent_Name.toString());
	}

	/**
	 * Set value of Parent_Name
	 * @param parent_name
	 */
	public final void setParent_Name(java.lang.String parent_name)
	{
		setParent_Name(getContext(), parent_name);
	}

	/**
	 * Set value of Parent_Name
	 * @param context
	 * @param parent_name
	 */
	public final void setParent_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parent_name)
	{
		getMendixObject().setValue(context, MemberNames.Parent_Name.toString(), parent_name);
	}

	/**
	 * @return value of Parent_email
	 */
	public final java.lang.String getParent_email()
	{
		return getParent_email(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_email
	 */
	public final java.lang.String getParent_email(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Parent_email.toString());
	}

	/**
	 * Set value of Parent_email
	 * @param parent_email
	 */
	public final void setParent_email(java.lang.String parent_email)
	{
		setParent_email(getContext(), parent_email);
	}

	/**
	 * Set value of Parent_email
	 * @param context
	 * @param parent_email
	 */
	public final void setParent_email(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parent_email)
	{
		getMendixObject().setValue(context, MemberNames.Parent_email.toString(), parent_email);
	}

	/**
	 * @return value of phone_number
	 */
	public final java.lang.Long getphone_number()
	{
		return getphone_number(getContext());
	}

	/**
	 * @param context
	 * @return value of phone_number
	 */
	public final java.lang.Long getphone_number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.phone_number.toString());
	}

	/**
	 * Set value of phone_number
	 * @param phone_number
	 */
	public final void setphone_number(java.lang.Long phone_number)
	{
		setphone_number(getContext(), phone_number);
	}

	/**
	 * Set value of phone_number
	 * @param context
	 * @param phone_number
	 */
	public final void setphone_number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long phone_number)
	{
		getMendixObject().setValue(context, MemberNames.phone_number.toString(), phone_number);
	}

	/**
	 * @return value of Parent_Registrant
	 */
	public final eventapplication.proxies.Registrant getParent_Registrant() throws com.mendix.core.CoreException
	{
		return getParent_Registrant(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_Registrant
	 */
	public final eventapplication.proxies.Registrant getParent_Registrant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.Registrant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_Registrant.toString());
		if (identifier != null)
			result = eventapplication.proxies.Registrant.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Parent_Registrant
	 * @param parent_registrant
	 */
	public final void setParent_Registrant(eventapplication.proxies.Registrant parent_registrant)
	{
		setParent_Registrant(getContext(), parent_registrant);
	}

	/**
	 * Set value of Parent_Registrant
	 * @param context
	 * @param parent_registrant
	 */
	public final void setParent_Registrant(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.Registrant parent_registrant)
	{
		if (parent_registrant == null)
			getMendixObject().setValue(context, MemberNames.Parent_Registrant.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Parent_Registrant.toString(), parent_registrant.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return parentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final eventapplication.proxies.Parent that = (eventapplication.proxies.Parent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EventApplication.Parent";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
