// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package eventapplication.proxies;

public class SpeakerPhoto extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EventApplication.SpeakerPhoto";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Speaker_SpeakerPhoto("EventApplication.Speaker_SpeakerPhoto");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SpeakerPhoto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EventApplication.SpeakerPhoto"));
	}

	protected SpeakerPhoto(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject speakerPhotoMendixObject)
	{
		super(context, speakerPhotoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("EventApplication.SpeakerPhoto", speakerPhotoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EventApplication.SpeakerPhoto");
	}

	/**
	 * @deprecated Use 'SpeakerPhoto.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static eventapplication.proxies.SpeakerPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return eventapplication.proxies.SpeakerPhoto.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static eventapplication.proxies.SpeakerPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new eventapplication.proxies.SpeakerPhoto(context, mendixObject);
	}

	public static eventapplication.proxies.SpeakerPhoto load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return eventapplication.proxies.SpeakerPhoto.initialize(context, mendixObject);
	}

	public static java.util.List<eventapplication.proxies.SpeakerPhoto> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<eventapplication.proxies.SpeakerPhoto> result = new java.util.ArrayList<eventapplication.proxies.SpeakerPhoto>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EventApplication.SpeakerPhoto" + xpathConstraint))
			result.add(eventapplication.proxies.SpeakerPhoto.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Speaker_SpeakerPhoto
	 */
	public final eventapplication.proxies.Speaker getSpeaker_SpeakerPhoto() throws com.mendix.core.CoreException
	{
		return getSpeaker_SpeakerPhoto(getContext());
	}

	/**
	 * @param context
	 * @return value of Speaker_SpeakerPhoto
	 */
	public final eventapplication.proxies.Speaker getSpeaker_SpeakerPhoto(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		eventapplication.proxies.Speaker result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Speaker_SpeakerPhoto.toString());
		if (identifier != null)
			result = eventapplication.proxies.Speaker.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Speaker_SpeakerPhoto
	 * @param speaker_speakerphoto
	 */
	public final void setSpeaker_SpeakerPhoto(eventapplication.proxies.Speaker speaker_speakerphoto)
	{
		setSpeaker_SpeakerPhoto(getContext(), speaker_speakerphoto);
	}

	/**
	 * Set value of Speaker_SpeakerPhoto
	 * @param context
	 * @param speaker_speakerphoto
	 */
	public final void setSpeaker_SpeakerPhoto(com.mendix.systemwideinterfaces.core.IContext context, eventapplication.proxies.Speaker speaker_speakerphoto)
	{
		if (speaker_speakerphoto == null)
			getMendixObject().setValue(context, MemberNames.Speaker_SpeakerPhoto.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Speaker_SpeakerPhoto.toString(), speaker_speakerphoto.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final eventapplication.proxies.SpeakerPhoto that = (eventapplication.proxies.SpeakerPhoto) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EventApplication.SpeakerPhoto";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
