// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package eventapplication.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the EventApplication module
	public static java.lang.String iNV_GetSpeakerName(IContext context, eventapplication.proxies.Speaker _speaker)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Speaker", _speaker == null ? null : _speaker.getMendixObject());
			return (java.lang.String)Core.execute(context, "EventApplication.INV_GetSpeakerName", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Long iNV_NumRegistrants(IContext context, eventapplication.proxies.Event _event)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Event", _event == null ? null : _event.getMendixObject());
			return (java.lang.Long)Core.execute(context, "EventApplication.INV_NumRegistrants", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Long iNV_NumSpotsAvailable(IContext context, eventapplication.proxies.Event _event)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Event", _event == null ? null : _event.getMendixObject());
			return (java.lang.Long)Core.execute(context, "EventApplication.INV_NumSpotsAvailable", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iNV_RegistrationCreate(IContext context, eventapplication.proxies.Event _event)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Event", _event == null ? null : _event.getMendixObject());
			Core.execute(context, "EventApplication.INV_RegistrationCreate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iNV_RegistrationSave(IContext context, eventapplication.proxies.Registrant _registrant)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Registrant", _registrant == null ? null : _registrant.getMendixObject());
			Core.execute(context, "EventApplication.INV_RegistrationSave", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void login_Validation(IContext context, eventapplication.proxies.Login _login)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Login", _login == null ? null : _login.getMendixObject());
			Core.execute(context, "EventApplication.Login_Validation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void parent_Login_Validation(IContext context, eventapplication.proxies.Login _login)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Login", _login == null ? null : _login.getMendixObject());
			Core.execute(context, "EventApplication.Parent_Login_Validation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void staff_Login_Validation(IContext context, eventapplication.proxies.Login _login)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Login", _login == null ? null : _login.getMendixObject());
			Core.execute(context, "EventApplication.Staff_Login_Validation", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}